name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
env:
  PYTHON_DEPLOYMENT_VERSION: 3.11
  ENV: prod


jobs:

  publish-cd-python-3_9:
    permissions:
      contents: read
      packages: write
    uses: settler-hackathon/github-templates/.github/workflows/python-cd.yml@main
    with:
      python-version: "3.9"
      ENV: $ENV
      REPO-NAME: "github-actions"


  publish-cd-python-3_10:
    permissions:
      contents: read
      packages: write
    uses: settler-hackathon/github-templates/.github/workflows/python-cd.yml@main
    with:
      python-version: "3.10"
      ENV: $ENV
      REPO-NAME: "github-actions"

  publish-cd-python-3_11:
    permissions:
      contents: read
      packages: write
    uses: settler-hackathon/github-templates/.github/workflows/python-cd.yml@main
    with:
      python-version: "3.11"
      ENV: $ENV
      REPO-NAME: "github-actions"


  publish-image-python-3_11:
    permissions:
      contents: read
      packages: write
    uses: settler-hackathon/github-templates/.github/workflows/python-push-image.yml@main
    with:
      ENV: $ENV
      REPO-NAME: "github-actions"
      PYTHON_DEPLOYMENT_VERSION: "3.11"