name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
env:
  PYTHON_DEPLOYMENT_VERSION: 3.11
  ENV: prod


jobs:
  publish-cd-python-3_9:
    uses: settler-hackathon/github-templates/.github/workflows/python-cd.yml@main
    with:
      python-version: "3.9"

  publish-cd-python-3_9:
    uses: settler-hackathon/github-templates/.github/workflows/python-cd.yml@main
    with:
      python-version: "3.10"
      PYTHON_DEPLOYMENT_VERSION: $PYTHON_DEPLOYMENT_VERSION
      ENV: $ENV