# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI PipelineTemplate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: settler-hackathon/github-templates/.github/workflows/python-ci.yml@main
      with:
        python-version: ${{ matrix.python-version }}

