# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # build-ci-python-3_9:
  #   uses: settler-hackathon/github-templates/.github/workflows/python-ci.yml@main
  #   with:
  #     python-version: "3.9"

  # build-ci-python-3_10:
  #   uses: settler-hackathon/github-templates/.github/workflows/python-ci.yml@main
  #   with:
  #     python-version: "3.10"

  build-ci-python-3_11:
    uses: settler-hackathon/github-templates/.github/workflows/python-ci.yml@main
    with:
      python-version: "3.11"
