name: Manual trigger

on:
  push:
      branches: [ "main" ]
  workflow_dispatch:


jobs:
  # test-versions:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version: ["3.9", "3.10", "3.11"]

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Confirmation that all went fine
  #     run: echo All went ok!

  build-image:
    permissions:
      contents: read
      packages: write
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build --build-arg PYTHON_VERSION=${{ matrix.python-version }} --build-arg ENV=dev -t ghcr.io/${{ github.repository_owner }}/github-actions_${{ matrix.python-version }}:latest .
      
      
      - name: start the docker image
        run: docker run -d -p 5000:5000 ghcr.io/${{ github.repository_owner }}/github-actions_${{ matrix.python-version }}:latest



      # - name: Lint with flake8
      #   run: flake8 .
      # - name: Check with isort
      #   if: always()
      #   run: isort . --check
      # - name: Check with PyRight
      #   if: always()
      #   run: pyright .
      # - name: Test with pytest
      #   run: |
      #     pytest
      # - name: Use Black from external
      #   if: always()
      #   uses: psf/black@stable
      #   with:
      #     options: "--check --verbose"
      #     src: "."
      #     version: "~= 23.9.1"
      # - name: Use Black
      #   if: always()
      #   run: black . --check --verbose
      # - name: Confirmation that all went fine
      #   run: echo All went ok!

  # docker push ghcr.io/${{ github.repository_owner }}/github-actions:latest
